server:
  port: 8082
spring:
  application:
    name: database-provider
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/liding
    username: yuan
    password: 123456
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 连接池最大连接数
      maximum-pool-size: 50
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接存活最大时间（毫秒）
      idle-timeout: 600000
      # 连接池最大存活时间（毫秒）
      max-lifetime: 1800000
      # 是否自动提交
      auto-commit: true
eureka:
  client:
    service-uri:
      defaultZone: http://admin:123456@localhost:8761/eureka/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印SQ


